### ISSUE TITLE
Composer.json "no matching package found"

### ISSUE THREAD

**Issue by marcaube** [robertotru/ToInlineStyleEmailBundle#5] opened 2013-09-04 18:13 UTC
It seems like composer can't find a `"dev-master"` branch for the dep. You should probably use the last stable tag for that package : `1.2.1`. I have `minimum-stability` set to `stable` in my `composer.json`.

This is what composer spits out: 

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for robertotru/to-inline-style-email-bundle dev-master -> satisfiable by robertotru/to-inline-style-email-bundle[dev-master].
    - robertotru/to-inline-style-email-bundle dev-master requires tijsverkoyen/css-to-inline-styles dev-master -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by cordoval** [comment] 2015-01-15 03:38
i think this is obvious because the package did not have a stable version because it was tagged 1.0.0-dev before, so this can be closed @Richtermeister

**Comment by Richtermeister** [comment] 2015-01-15 03:39
We have a stable tag 1.1.0 now.

**Comment by taylankasap** [comment] 2015-10-16 12:01
What about now?

Command: `composer require robertotru/to-inline-style-email-bundle`
Output:
```
[InvalidArgumentException]
  Could not find package robertotru/to-inline-style-email-bundle at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
```

**Comment by Richtermeister** [comment] 2015-10-16 17:01
Hmmm, gonna look into that.

**Comment by cordoval** [comment] 2017-06-01 21:14
@taylankasap please edit rather the composer.json and specify a version for your dependency.

**Comment by cordoval** [comment] 2017-06-02 13:26
@marcaube @taylankasap please paste a composer.json so i can reproduce

i think this is because the dep back then was not specifically set to a version but now it is so this is a no issue now.

**Comment by taylankasap** [comment] 2017-06-02 13:32
Hey @cordoval. My comment is 2 years old so I don't really remember anything about this. I think you can close this issue if it works with default Symfony2 and Symfony3 installations.

**Comment by cordoval** [comment] 2017-06-02 13:33
thanks @taylankasap 👍 👴

**Closed** 2017-06-02 13:33 UTC
